name: CI - Compile TypeScript

on:
  push:
    branches:
      - main

jobs:
  compile-ts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install

      - name: Compile TypeScript
        run: npm run typecheck

      - name: Check TypeScript status
        run: |
          if [ $? -ne 0 ]; then
            echo "TypeScript compilation failed."
            exit 1
          fi
