name: CI - Build, Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
          npm cache clean --force
          npm install

    - name: Run Cypress tests
      uses: cypress-io/github-action@v6.1.0
      with:
        start: npm run test &
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 60 # Waits for 1 minute for the server to start
        command: npm run cypress:run # This explicitly runs Cypress tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Status
      if: failure()
      run: exit 1
